# Generated by Django 4.1.5 on 2023-01-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_logo', models.ImageField(blank=True, null=True, upload_to='files/clinicLogo')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Medication_Size', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('ReStock_Level', models.IntegerField(blank=True, null=True)),
                ('Qr_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Medication_Image', models.ImageField(blank=True, null=True, upload_to='files/Medication')),
                ('Qr_image', models.ImageField(blank=True, null=True, upload_to='files/Qr_Codes')),
                ('shelf', models.CharField(blank=True, default='Yes', max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateField', models.DateField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Take', models.CharField(blank=True, max_length=200, null=True)),
                ('Times', models.CharField(blank=True, max_length=200, null=True)),
                ('Hours', models.CharField(blank=True, max_length=200, null=True)),
                ('ExpireDate', models.DateField(null=True)),
                ('before', models.CharField(blank=True, max_length=200, null=True)),
                ('after', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, default='No', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Medication_ID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_id', to='client.inventorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Medication_ID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseket', to='client.inventorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('dateField', models.DateField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Medication_ID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complete', to='client.inventorymodel')),
            ],
        ),
    ]
